/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcCalvingDateActions {
    'socket': string;
    'tract': string;
  }
  interface AgcCalvingDateActionsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
    'tract'?: string;
  }

  interface AgcCalvingDateProgress {
    'socket': string;
  }
  interface AgcCalvingDateProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCalvingDateAction {
    'action': 'reset' | 'move';
    'actionText': string;
    'socket': string;
  }
  interface AgcCalvingDateActionAttributes extends StencilHTMLAttributes {
    'action'?: 'reset' | 'move';
    'actionText'?: string;
    'onAgcAction'?: (event: CustomEvent) => void;
    'socket'?: string;
  }

  interface AgcCalvingDateResultsPlaceholder {}
  interface AgcCalvingDateResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcCalvingDateResults {
    'socket': string;
  }
  interface AgcCalvingDateResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCalvingDate {
    'mode': 'full' | 'step';
    'shadow': boolean;
    'socket': string;
    'tract': string;
  }
  interface AgcCalvingDateAttributes extends StencilHTMLAttributes {
    'mode'?: 'full' | 'step';
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'shadow'?: boolean;
    'socket'?: string;
    'tract'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcCalvingDateActions': Components.AgcCalvingDateActions;
    'AgcCalvingDateProgress': Components.AgcCalvingDateProgress;
    'AgcCalvingDateAction': Components.AgcCalvingDateAction;
    'AgcCalvingDateResultsPlaceholder': Components.AgcCalvingDateResultsPlaceholder;
    'AgcCalvingDateResults': Components.AgcCalvingDateResults;
    'AgcCalvingDate': Components.AgcCalvingDate;
  }

  interface StencilIntrinsicElements {
    'agc-calving-date-actions': Components.AgcCalvingDateActionsAttributes;
    'agc-calving-date-progress': Components.AgcCalvingDateProgressAttributes;
    'agc-calving-date-action': Components.AgcCalvingDateActionAttributes;
    'agc-calving-date-results-placeholder': Components.AgcCalvingDateResultsPlaceholderAttributes;
    'agc-calving-date-results': Components.AgcCalvingDateResultsAttributes;
    'agc-calving-date': Components.AgcCalvingDateAttributes;
  }


  interface HTMLAgcCalvingDateActionsElement extends Components.AgcCalvingDateActions, HTMLStencilElement {}
  var HTMLAgcCalvingDateActionsElement: {
    prototype: HTMLAgcCalvingDateActionsElement;
    new (): HTMLAgcCalvingDateActionsElement;
  };

  interface HTMLAgcCalvingDateProgressElement extends Components.AgcCalvingDateProgress, HTMLStencilElement {}
  var HTMLAgcCalvingDateProgressElement: {
    prototype: HTMLAgcCalvingDateProgressElement;
    new (): HTMLAgcCalvingDateProgressElement;
  };

  interface HTMLAgcCalvingDateActionElement extends Components.AgcCalvingDateAction, HTMLStencilElement {}
  var HTMLAgcCalvingDateActionElement: {
    prototype: HTMLAgcCalvingDateActionElement;
    new (): HTMLAgcCalvingDateActionElement;
  };

  interface HTMLAgcCalvingDateResultsPlaceholderElement extends Components.AgcCalvingDateResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcCalvingDateResultsPlaceholderElement: {
    prototype: HTMLAgcCalvingDateResultsPlaceholderElement;
    new (): HTMLAgcCalvingDateResultsPlaceholderElement;
  };

  interface HTMLAgcCalvingDateResultsElement extends Components.AgcCalvingDateResults, HTMLStencilElement {}
  var HTMLAgcCalvingDateResultsElement: {
    prototype: HTMLAgcCalvingDateResultsElement;
    new (): HTMLAgcCalvingDateResultsElement;
  };

  interface HTMLAgcCalvingDateElement extends Components.AgcCalvingDate, HTMLStencilElement {}
  var HTMLAgcCalvingDateElement: {
    prototype: HTMLAgcCalvingDateElement;
    new (): HTMLAgcCalvingDateElement;
  };

  interface HTMLElementTagNameMap {
    'agc-calving-date-actions': HTMLAgcCalvingDateActionsElement
    'agc-calving-date-progress': HTMLAgcCalvingDateProgressElement
    'agc-calving-date-action': HTMLAgcCalvingDateActionElement
    'agc-calving-date-results-placeholder': HTMLAgcCalvingDateResultsPlaceholderElement
    'agc-calving-date-results': HTMLAgcCalvingDateResultsElement
    'agc-calving-date': HTMLAgcCalvingDateElement
  }

  interface ElementTagNameMap {
    'agc-calving-date-actions': HTMLAgcCalvingDateActionsElement;
    'agc-calving-date-progress': HTMLAgcCalvingDateProgressElement;
    'agc-calving-date-action': HTMLAgcCalvingDateActionElement;
    'agc-calving-date-results-placeholder': HTMLAgcCalvingDateResultsPlaceholderElement;
    'agc-calving-date-results': HTMLAgcCalvingDateResultsElement;
    'agc-calving-date': HTMLAgcCalvingDateElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
