/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcCalvingDateProgress {
    'socket': string;
  }
  interface AgcCalvingDateProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcCalvingDateAction {
    'action': 'reset' | 'move';
    'actionText': string;
    'socket': string;
  }
  interface AgcCalvingDateActionAttributes extends StencilHTMLAttributes {
    'action'?: 'reset' | 'move';
    'actionText'?: string;
    'onAgcAction'?: (event: CustomEvent) => void;
    'socket'?: string;
  }

  interface AgcCalvingDate {
    'shadow': boolean;
    'socket': string;
  }
  interface AgcCalvingDateAttributes extends StencilHTMLAttributes {
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'shadow'?: boolean;
    'socket'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcCalvingDateProgress': Components.AgcCalvingDateProgress;
    'AgcCalvingDateAction': Components.AgcCalvingDateAction;
    'AgcCalvingDate': Components.AgcCalvingDate;
  }

  interface StencilIntrinsicElements {
    'agc-calving-date-progress': Components.AgcCalvingDateProgressAttributes;
    'agc-calving-date-action': Components.AgcCalvingDateActionAttributes;
    'agc-calving-date': Components.AgcCalvingDateAttributes;
  }


  interface HTMLAgcCalvingDateProgressElement extends Components.AgcCalvingDateProgress, HTMLStencilElement {}
  var HTMLAgcCalvingDateProgressElement: {
    prototype: HTMLAgcCalvingDateProgressElement;
    new (): HTMLAgcCalvingDateProgressElement;
  };

  interface HTMLAgcCalvingDateActionElement extends Components.AgcCalvingDateAction, HTMLStencilElement {}
  var HTMLAgcCalvingDateActionElement: {
    prototype: HTMLAgcCalvingDateActionElement;
    new (): HTMLAgcCalvingDateActionElement;
  };

  interface HTMLAgcCalvingDateElement extends Components.AgcCalvingDate, HTMLStencilElement {}
  var HTMLAgcCalvingDateElement: {
    prototype: HTMLAgcCalvingDateElement;
    new (): HTMLAgcCalvingDateElement;
  };

  interface HTMLElementTagNameMap {
    'agc-calving-date-progress': HTMLAgcCalvingDateProgressElement
    'agc-calving-date-action': HTMLAgcCalvingDateActionElement
    'agc-calving-date': HTMLAgcCalvingDateElement
  }

  interface ElementTagNameMap {
    'agc-calving-date-progress': HTMLAgcCalvingDateProgressElement;
    'agc-calving-date-action': HTMLAgcCalvingDateActionElement;
    'agc-calving-date': HTMLAgcCalvingDateElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
